import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import Header from "../components/header"; // Import header

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Header /> {/* Injected here */}
        {children}
      </body>
    </html>
  );
}
